# Generated by Django 2.2.4 on 2020-04-16 16:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GolfCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
                ('hole_one_par', models.IntegerField()),
                ('hole_two_par', models.IntegerField()),
                ('hole_three_par', models.IntegerField()),
                ('hole_four_par', models.IntegerField()),
                ('hole_five_par', models.IntegerField()),
                ('hole_six_par', models.IntegerField()),
                ('hole_seven_par', models.IntegerField()),
                ('hole_eight_par', models.IntegerField()),
                ('hole_nine_par', models.IntegerField()),
                ('hole_ten_par', models.IntegerField()),
                ('hole_eleven_par', models.IntegerField()),
                ('hole_twelve_par', models.IntegerField()),
                ('hole_thirteen_par', models.IntegerField()),
                ('hole_fourteen_par', models.IntegerField()),
                ('hole_fifteen_par', models.IntegerField()),
                ('hole_sixteen_par', models.IntegerField()),
                ('hole_seventeen_par', models.IntegerField()),
                ('hole_eighteen_par', models.IntegerField()),
                ('total_par', models.IntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
                ('hole_one', models.IntegerField()),
                ('hole_two', models.IntegerField()),
                ('hole_three', models.IntegerField()),
                ('hole_four', models.IntegerField()),
                ('hole_five', models.IntegerField()),
                ('hole_six', models.IntegerField()),
                ('hole_seven', models.IntegerField()),
                ('hole_eight', models.IntegerField()),
                ('hole_nine', models.IntegerField()),
                ('hole_ten', models.IntegerField()),
                ('hole_eleven', models.IntegerField()),
                ('hole_twelve', models.IntegerField()),
                ('hole_thirteen', models.IntegerField()),
                ('hole_fourteen', models.IntegerField()),
                ('hole_fifteen', models.IntegerField()),
                ('hole_sixteen', models.IntegerField()),
                ('hole_seventeen', models.IntegerField()),
                ('hole_eighteen', models.IntegerField()),
                ('total_score', models.IntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
