# Generated by Django 2.2.4 on 2020-04-16 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0002_auto_20200416_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hole_one', models.IntegerField()),
                ('hole_two', models.IntegerField()),
                ('hole_three', models.IntegerField()),
                ('hole_four', models.IntegerField()),
                ('hole_five', models.IntegerField()),
                ('hole_six', models.IntegerField()),
                ('hole_seven', models.IntegerField()),
                ('hole_eight', models.IntegerField()),
                ('hole_nine', models.IntegerField()),
                ('hole_ten', models.IntegerField()),
                ('hole_eleven', models.IntegerField()),
                ('hole_twelve', models.IntegerField()),
                ('hole_thirteen', models.IntegerField()),
                ('hole_fourteen', models.IntegerField()),
                ('hole_fifteen', models.IntegerField()),
                ('hole_sixteen', models.IntegerField()),
                ('hole_seventeen', models.IntegerField()),
                ('hole_eighteen', models.IntegerField()),
                ('total_score', models.IntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='crm.GolfCourse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Scores',
        ),
    ]
