# Generated by Django 2.2.4 on 2020-04-16 20:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20200416_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='golf_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
